import Config

# Spotify OAuth credentials (set these in your environment or here for dev)
config :music_dance_experience,
  spotify_client_id: System.get_env("SPOTIFY_CLIENT_ID") || "REDACTED_CLIENT_ID",
  spotify_client_secret: System.get_env("SPOTIFY_CLIENT_SECRET") || "REDACTED_CLIENT_SECRET",
  spotify_redirect_uri: System.get_env("SPOTIFY_REDIRECT_URI") || "http://localhost:4000/auth/spotify/callback",
  app_password: System.get_env("APP_PASSWORD") || "lumon"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :music_dance_experience, MusicDanceExperienceWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "SME0gtAvUQ5ToaOQtO6a/XjevdDnplZsXwIDuWYrBueIyMfDHnVOBqhI0TAWhm26",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:music_dance_experience, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:music_dance_experience, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :music_dance_experience, MusicDanceExperienceWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/music_dance_experience_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

config :music_dance_experience, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
